worldListenAddress: "0.0.0.0"
worldListenPort: 8010

playerListenAddress: "0.0.0.0"
playerListenPort: 8011

dataserverIP: "127.0.0.1"
dataserverPORT: 8001

#in seconds, how often do send a heartbeat to all connected world servers
worldHeartbeatInterval: 10


defaultServer: "desert"

worlds:
  - desert: 2
  - beach: 2
  - crypts: 3
  - forest: 1
