#the config for the comms server says what?
#how many of each world type to load

worldListenAddress: "0.0.0.0"
worldListenPort: 8010

playerListenAddress: "0.0.0.0"
playerListenPort: 8011

dataserverIP: "127.0.0.1"
dataserverPORT: 8001


#alright, so we are setting up our world, we want to be able to tell it how many servers of each type, so what?
#okay say the type and number of servers to setup? handle load balancing by sending to the lowest amount of players, 
#currently it cant start any servers

defaultServer: "desert"

worlds:
  - desert: 2
  - caves: 1
  - crypts: 1
  - beach: 1
