#  remember we are going to have multiple servers of say desert, all of them must have same number of entities in same locations
#  eventually your going to be able to chop down trees, or cut down cactuses, so they must be able to 'regrow' over time, this can change depending on the World
#  
#  so static entities also need to have a hitbox? how big?, how long, how much health? how many hits to cut down, right, maybe a health system
#  okay so every static entity has an x, y and health at base
#  crops are a child of so, they also have growth stages, and change images based on the growth stage, should this be moddable?
#  
#  
#  okay so we have predfined static entities that you can add to your World, similar to tiles, have a folder for them

#   okay so we are adding static entities to the world, they have collision, an image, and possibly an animation
#   they can be chopped/mined/harvested for resources, they can have growth stages, and times between stages
#   
#
#
#



cactus:
    - [100, 100]
    - [200, 100]

redrock2:
    - [100, 500]

redrock3:
    - [100, 700]